/**
 * Google Drive API Service
 * Handles listing, reading, and exporting study plans to user's Google Drive
 */

export interface GoogleDriveFile {
  id: string;
  name: string;
  mimeType: string;
  modifiedTime?: string;
  size?: string;
  iconLink?: string;
  webViewLink?: string;
}

/**
 * List files from Google Drive (prioritizing PDFs, Docs, text files, and course materials)
 */
export async function listDriveFiles(
  accessToken: string,
  searchQuery?: string
): Promise<GoogleDriveFile[]> {
  let query = "trashed = false";
  if (searchQuery && searchQuery.trim()) {
    query += ` and name contains '${searchQuery.replace(/'/g, "\\'")}'`;
  } else {
    // Show documents, pdfs, and text by default
    query += " and (mimeType = 'application/pdf' or mimeType = 'application/vnd.google-apps.document' or mimeType = 'text/plain' or mimeType = 'text/markdown' or mimeType = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document')";
  }

  const url = new URL('https://www.googleapis.com/drive/v3/files');
  url.searchParams.set('q', query);
  url.searchParams.set('pageSize', '25');
  url.searchParams.set(
    'fields',
    'nextPageToken, files(id, name, mimeType, modifiedTime, size, iconLink, webViewLink)'
  );
  url.searchParams.set('orderBy', 'modifiedTime desc');

  const res = await fetch(url.toString(), {
    headers: {
      Authorization: `Bearer ${accessToken}`,
      Accept: 'application/json',
    },
  });

  if (!res.ok) {
    const errorData = await res.json().catch(() => ({}));
    throw new Error(
      errorData.error?.message || `Failed to fetch Google Drive files (status ${res.status})`
    );
  }

  const data = await res.json();
  return data.files || [];
}

/**
 * Read text content from a Google Drive file
 * - For Google Docs: exports as text/plain
 * - For text/markdown/plain files: fetches directly
 */
export async function readDriveFileContent(
  accessToken: string,
  fileId: string,
  mimeType: string
): Promise<string> {
  let endpoint = `https://www.googleapis.com/drive/v3/files/${fileId}?alt=media`;

  if (mimeType === 'application/vnd.google-apps.document') {
    endpoint = `https://www.googleapis.com/drive/v3/files/${fileId}/export?mimeType=text/plain`;
  }

  const res = await fetch(endpoint, {
    headers: {
      Authorization: `Bearer ${accessToken}`,
    },
  });

  if (!res.ok) {
    throw new Error(`Failed to read file from Google Drive (${res.status})`);
  }

  return await res.text();
}

/**
 * Upload or export a Study Plan to Google Drive
 */
export async function exportStudyPlanToDrive(
  accessToken: string,
  title: string,
  content: string
): Promise<{ id: string; name: string; webViewLink?: string }> {
  const metadata = {
    name: `${title}.md`,
    mimeType: 'text/markdown',
    description: 'Generated by Synapse AI Syllabus-to-Study-Plan Engine',
  };

  const boundary = '-------314159265358979323846';
  const delimiter = `\r\n--${boundary}\r\n`;
  const closeDelimiter = `\r\n--${boundary}--`;

  const multipartRequestBody =
    delimiter +
    'Content-Type: application/json; charset=UTF-8\r\n\r\n' +
    JSON.stringify(metadata) +
    delimiter +
    'Content-Type: text/markdown\r\n\r\n' +
    content +
    closeDelimiter;

  const res = await fetch(
    'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,webViewLink',
    {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${accessToken}`,
        'Content-Type': `multipart/related; boundary=${boundary}`,
      },
      body: multipartRequestBody,
    }
  );

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err.error?.message || `Failed to upload file to Google Drive (${res.status})`);
  }

  return await res.json();
}
